services:
    sonata.admin.user:
        class: AdminBundle\Admin\UserAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Website entities"
              label: "User"
        arguments:
            - ~
            - Dragonfly\Model\User
            - AdminBundle:User
