security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                login_path: /
                always_use_default_target_path: true
                default_target_path: /panel
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: user.login_success_handler
            logout:       true
            anonymous:    true

        default:
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/panel/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
